conf:
  cache_type: db
  database_type: mysql
  node: 1
  listen: 0.0.0.0:9000
db:
  host:  '[::1]'
  port: 3306
  user: root
  password: 123456
  database: CloudPrinter
cos:
  appid: 123123123
  bucket: test-123123123
  region: ap-beijing
secret:
  secret_id: AKIDd5xxxxxxxxxxxxxxxxxxxxxxxx
  secret_key: GG2cxxxxxxxxxxxxxxxxxxxxxxxx
redis:
  host: localhost
  port: 6379
  password:
  db: 0
wechat:
  appid: wxcabcefdgdffeddf
  secret: abcabcabcabcabcabcabcabc
pay:
  mch_id: 123123123
  key: cnaaaaaaaaaaa